Added functionality to convert a string to an array of specified type
padaiyal/jUnitTestExtras pull request #6
Opened 2021-05-19 05:14 UTC by silvs110

## Description
Added functionality to convert a string to an array of specified type.

Closes #4.

## Author's Checklist
- [x] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.**
- [ ] **All methods have documentation comments.**
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. 
- [ ] **README.md has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

2021-05-19 05:38 UTC, the-c0d3br34k3r commented on pom.xml
>        <url>https://maven.pkg.github.com/padaiyal/jMavenProjectTemplate</url>
```suggestion
      <url>https://maven.pkg.github.com/padaiyal/jUnitTestExtras</url>
```

2021-05-19 06:50 UTC, the-c0d3br34k3r requested changes
Reviewed. Have requested changes and have a dded a few enhancements.

2021-05-20 22:40 UTC, silvs110 commented on pom.xml
>        <url>https://maven.pkg.github.com/padaiyal/jMavenProjectTemplate</url>
done

2021-05-21 14:25 UTC, the-c0d3br34k3r approved these changes

2021-05-21 14:26 UTC, merged