Added annotation for ranged source used in parameterized tests
padaiyal/jUnitTestExtras pull request #7
Opened 2021-05-20 22:44 UTC by silvs110

## Description

Added annotation that allows to run a test with input parameters within a numeric range.
Implementation is similar to the one described here: https://objectpartners.com/2018/06/12/create-a-custom-annotation-for-your-junit5-parameterizedtest-argumentprovider/

Closes #1.

## Author's Checklist
- [x] **These changes don't break existing dependants.** If they do, and you suggest to proceed, 
please explain why.

## Reviewer's Checklist
- [ ] **All classes have documentation comments.**
- [ ] **All methods have documentation comments.**
- [ ] **No parameters are hardcoded.** Should be loaded as properties instead. If there needs to be hardcoded properties, explain why.
- [ ] **All information to be logged/displayed to the user are internationalized.** If not, explain why. 
- [ ] **README.md has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

## Assignee's Checklist
- [ ] **All GitHub action checks have passed.**
- [ ] **All reviewers have approved.**
- [ ] **Relevant documentation has been updated if needed.**
- [ ] **pom.xml version is set to the latest date** If not, explain why.

2021-05-21 14:27 UTC, the-c0d3br34k3r requested changes
Please rebase with main.

2021-05-21 14:27 UTC, the-c0d3br34k3r commented on src/main/java/org/padaiyal/utilities/unittestextras/annotations/RangedArgumentsProvider.java
> +        .parallel()
Why is parallel() in between?

2021-05-23 01:43 UTC, silvs110 commented on src/main/java/org/padaiyal/utilities/unittestextras/annotations/RangedArgumentsProvider.java
> +        .parallel()
done

2021-05-30 17:08 UTC, the-c0d3br34k3r approved these changes

2021-05-30 17:11 UTC, merged